name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Check spotless
      run: ./gradlew spotlessCheck --no-configuration-cache

    - name: Build debug with github flavor
      run: ./gradlew assembleGithubDebug

    - name: Upload build outputs (APKs)
      uses: actions/upload-artifact@v3
      with:
        name: APKs
        path: '**/build/outputs/apk/**/*.apk'

  apk:
    name: APK
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v3
      id: download
      with:
        name: APKs

    - name: Display structure of downloaded files
      run: ls -R

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
